# Server url
# Local server configuration at: https://docs.minimals.cc/mock-server/
# NEXT_PUBLIC_SERVER_URL=http://localhost:7272
NEXT_PUBLIC_SERVER_URL=https://api-dev-minimal-v700.pages.dev

# Public resource directory
NEXT_PUBLIC_ASSETS_DIR=

# Mapbox
NEXT_PUBLIC_MAPBOX_API_KEY=

# Firebase
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=
NEXT_PUBLIC_FIREBASE_PROJECT_ID=
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APPID=

# Aws
NEXT_PUBLIC_AWS_AMPLIFY_USER_POOL_ID=
NEXT_PUBLIC_AWS_AMPLIFY_USER_POOL_WEB_CLIENT_ID=
NEXT_PUBLIC_AWS_AMPLIFY_REGION=


# Auth0
NEXT_PUBLIC_AUTH0_DOMAIN=
NEXT_PUBLIC_AUTH0_CLIENT_ID=
NEXT_PUBLIC_AUTH0_CALLBACK_URL=

# Supabase
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
